# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/change_category_name_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_category_name_dialog(object):
    def setupUi(self, change_category_name_dialog):
        change_category_name_dialog.setObjectName("change_category_name_dialog")
        change_category_name_dialog.resize(400, 300)
        change_category_name_dialog.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QLineEdit { \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {    /* zmiana kolorów listy rozwijanej */\n"
"    background-color: #202020;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(change_category_name_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.change_category_line_edit = QtWidgets.QLineEdit(change_category_name_dialog)
        self.change_category_line_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.change_category_line_edit.setObjectName("change_category_line_edit")
        self.gridLayout.addWidget(self.change_category_line_edit, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(change_category_name_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.change_category_combobox = QtWidgets.QComboBox(change_category_name_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_category_combobox.sizePolicy().hasHeightForWidth())
        self.change_category_combobox.setSizePolicy(sizePolicy)
        self.change_category_combobox.setMinimumSize(QtCore.QSize(0, 40))
        self.change_category_combobox.setObjectName("change_category_combobox")
        self.gridLayout.addWidget(self.change_category_combobox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(change_category_name_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(change_category_name_dialog)
        self.buttonBox.accepted.connect(change_category_name_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(change_category_name_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(change_category_name_dialog)

    def retranslateUi(self, change_category_name_dialog):
        _translate = QtCore.QCoreApplication.translate
        change_category_name_dialog.setWindowTitle(_translate("change_category_name_dialog", "Dialog"))
        self.label.setText(_translate("change_category_name_dialog", "Wybierz kategorię, której nazwę chcesz zmienić, a następnie wpisz nową nazwę:"))
