# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kubus/Pulpit/Wydatkoinator/ui/choose_columns_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_columns_csv(object):
    def setupUi(self, choose_columns_csv):
        choose_columns_csv.setObjectName("choose_columns_csv")
        choose_columns_csv.resize(700, 700)
        choose_columns_csv.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QTableWidget { \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    background-color: #3e3e3e; \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:vertical {\n"
"    background-color: #3e3e3e; \n"
"}\n"
"\n"
"QScrollBar {\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(choose_columns_csv)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(choose_columns_csv)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.table_csv = QtWidgets.QTableWidget(choose_columns_csv)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.table_csv.setFont(font)
        self.table_csv.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_csv.setObjectName("table_csv")
        self.table_csv.setColumnCount(0)
        self.table_csv.setRowCount(0)
        self.gridLayout.addWidget(self.table_csv, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(choose_columns_csv)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.date_column = QtWidgets.QLineEdit(choose_columns_csv)
        self.date_column.setObjectName("date_column")
        self.gridLayout.addWidget(self.date_column, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(choose_columns_csv)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.amount_column = QtWidgets.QLineEdit(choose_columns_csv)
        self.amount_column.setObjectName("amount_column")
        self.gridLayout.addWidget(self.amount_column, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(choose_columns_csv)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.description_column = QtWidgets.QLineEdit(choose_columns_csv)
        self.description_column.setObjectName("description_column")
        self.gridLayout.addWidget(self.description_column, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(choose_columns_csv)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(choose_columns_csv)
        self.buttonBox.accepted.connect(choose_columns_csv.accept) # type: ignore
        self.buttonBox.rejected.connect(choose_columns_csv.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(choose_columns_csv)

    def retranslateUi(self, choose_columns_csv):
        _translate = QtCore.QCoreApplication.translate
        choose_columns_csv.setWindowTitle(_translate("choose_columns_csv", "Dialog"))
        self.label.setText(_translate("choose_columns_csv", "Wybrany plik csv:"))
        self.label_2.setText(_translate("choose_columns_csv", "Wpisz numer kolumny z datą:"))
        self.label_3.setText(_translate("choose_columns_csv", "Wpisz numer kolumny z kwotą:"))
        self.label_4.setText(_translate("choose_columns_csv", "Wpisz numer kolumny z opisem (może być więcej niż 1):"))
