# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/csv_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_csv_dialog(object):
    def setupUi(self, csv_dialog):
        csv_dialog.setObjectName("csv_dialog")
        csv_dialog.resize(400, 300)
        csv_dialog.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QLineEdit {\n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QComboBox{ \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {    /* zmiana kolorów listy rozwijanej */\n"
"    background-color: #202020;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(csv_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(csv_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.date_line_edit = QtWidgets.QLineEdit(csv_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_line_edit.sizePolicy().hasHeightForWidth())
        self.date_line_edit.setSizePolicy(sizePolicy)
        self.date_line_edit.setMinimumSize(QtCore.QSize(120, 30))
        self.date_line_edit.setObjectName("date_line_edit")
        self.gridLayout.addWidget(self.date_line_edit, 1, 0, 1, 1)
        self.amount_line_edit = QtWidgets.QLineEdit(csv_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_line_edit.sizePolicy().hasHeightForWidth())
        self.amount_line_edit.setSizePolicy(sizePolicy)
        self.amount_line_edit.setMinimumSize(QtCore.QSize(120, 30))
        self.amount_line_edit.setObjectName("amount_line_edit")
        self.gridLayout.addWidget(self.amount_line_edit, 1, 1, 1, 1)
        self.category_combobox = QtWidgets.QComboBox(csv_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_combobox.sizePolicy().hasHeightForWidth())
        self.category_combobox.setSizePolicy(sizePolicy)
        self.category_combobox.setMinimumSize(QtCore.QSize(120, 30))
        self.category_combobox.setObjectName("category_combobox")
        self.gridLayout.addWidget(self.category_combobox, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(csv_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 3)
        self.description_text_edit = QtWidgets.QPlainTextEdit(csv_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.description_text_edit.setFont(font)
        self.description_text_edit.setObjectName("description_text_edit")
        self.gridLayout.addWidget(self.description_text_edit, 3, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(csv_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 3)

        self.retranslateUi(csv_dialog)
        self.buttonBox.accepted.connect(csv_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(csv_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(csv_dialog)

    def retranslateUi(self, csv_dialog):
        _translate = QtCore.QCoreApplication.translate
        csv_dialog.setWindowTitle(_translate("csv_dialog", "Dialog"))
        self.label.setText(_translate("csv_dialog", "Odczytano:"))
        self.label_2.setText(_translate("csv_dialog", "Dobierz kategorię na podstawie poniższego opisu:"))
