# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/delete_category_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_category_dialog(object):
    def setupUi(self, delete_category_dialog):
        delete_category_dialog.setObjectName("delete_category_dialog")
        delete_category_dialog.resize(400, 300)
        delete_category_dialog.setMinimumSize(QtCore.QSize(0, 50))
        delete_category_dialog.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QComboBox{ \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {    /* zmiana kolorów listy rozwijanej */\n"
"    background-color: #202020;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(delete_category_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(delete_category_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.delete_category_combobox = QtWidgets.QComboBox(delete_category_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_category_combobox.sizePolicy().hasHeightForWidth())
        self.delete_category_combobox.setSizePolicy(sizePolicy)
        self.delete_category_combobox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_category_combobox.setFont(font)
        self.delete_category_combobox.setObjectName("delete_category_combobox")
        self.gridLayout.addWidget(self.delete_category_combobox, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(delete_category_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(delete_category_dialog)
        self.buttonBox.accepted.connect(delete_category_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(delete_category_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(delete_category_dialog)

    def retranslateUi(self, delete_category_dialog):
        _translate = QtCore.QCoreApplication.translate
        delete_category_dialog.setWindowTitle(_translate("delete_category_dialog", "Dialog"))
        self.label.setText(_translate("delete_category_dialog", "Wybierz kategorię, którą chcesz usunąć:"))
