# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/expenses_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_expenses_tab(object):
    def setupUi(self, expenses_tab):
        expenses_tab.setObjectName("expenses_tab")
        expenses_tab.resize(1145, 693)
        expenses_tab.setStyleSheet("QWidget {\n"
"background: #202020}\n"
"\n"
"QFrame {\n"
"background: #252525 }\n"
"\n"
"QLabel {\n"
"color: #c8beb7;\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: #182B32;\n"
"color: #c8beb7;\n"
"}\n"
"\n"
"QComboBox {\n"
"background-color: #3e3e3e;\n"
"color: #c8beb7;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background-color: #3e3e3e;\n"
"color: #c8beb7;\n"
"}\n"
"\n"
"QDateEdit {\n"
"background-color: #3e3e3e;\n"
"color: #c8beb7;\n"
"}\n"
"\n"
"QListWidget { color: #c8beb7; }\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(expenses_tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(expenses_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browse_file_line_edit = QtWidgets.QLineEdit(self.frame_3)
        self.browse_file_line_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.browse_file_line_edit.setObjectName("browse_file_line_edit")
        self.gridLayout_3.addWidget(self.browse_file_line_edit, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 3)
        self.add_expense_csv_label = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_expense_csv_label.sizePolicy().hasHeightForWidth())
        self.add_expense_csv_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_expense_csv_label.setFont(font)
        self.add_expense_csv_label.setObjectName("add_expense_csv_label")
        self.gridLayout_3.addWidget(self.add_expense_csv_label, 1, 0, 1, 3, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 2, 1, 1)
        self.choose_file_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.choose_file_label.setFont(font)
        self.choose_file_label.setObjectName("choose_file_label")
        self.gridLayout_3.addWidget(self.choose_file_label, 3, 0, 1, 1)
        self.browse_file_button = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_file_button.sizePolicy().hasHeightForWidth())
        self.browse_file_button.setSizePolicy(sizePolicy)
        self.browse_file_button.setMinimumSize(QtCore.QSize(0, 40))
        self.browse_file_button.setObjectName("browse_file_button")
        self.gridLayout_3.addWidget(self.browse_file_button, 3, 2, 1, 1)
        self.ok_button_csv = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_button_csv.sizePolicy().hasHeightForWidth())
        self.ok_button_csv.setSizePolicy(sizePolicy)
        self.ok_button_csv.setMinimumSize(QtCore.QSize(216, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ok_button_csv.setFont(font)
        self.ok_button_csv.setObjectName("ok_button_csv")
        self.gridLayout_3.addWidget(self.ok_button_csv, 5, 1, 1, 2, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_3, 2, 2, 1, 1)
        self.frame = QtWidgets.QFrame(expenses_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.categories_list_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.categories_list_label.setFont(font)
        self.categories_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.categories_list_label.setObjectName("categories_list_label")
        self.gridLayout_5.addWidget(self.categories_list_label, 0, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 378, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.categories_list_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories_list_list.sizePolicy().hasHeightForWidth())
        self.categories_list_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.categories_list_list.setFont(font)
        self.categories_list_list.setAlternatingRowColors(False)
        self.categories_list_list.setItemAlignment(QtCore.Qt.AlignCenter)
        self.categories_list_list.setObjectName("categories_list_list")
        self.gridLayout_4.addWidget(self.categories_list_list, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.add_category_button = QtWidgets.QPushButton(self.frame)
        self.add_category_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_category_button.setFont(font)
        self.add_category_button.setObjectName("add_category_button")
        self.gridLayout_5.addWidget(self.add_category_button, 2, 0, 1, 1)
        self.delete_category_button = QtWidgets.QPushButton(self.frame)
        self.delete_category_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delete_category_button.setFont(font)
        self.delete_category_button.setObjectName("delete_category_button")
        self.gridLayout_5.addWidget(self.delete_category_button, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 3, 1)
        self.frame_2 = QtWidgets.QFrame(expenses_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.category_label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.category_label.setFont(font)
        self.category_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.category_label.setObjectName("category_label")
        self.gridLayout_2.addWidget(self.category_label, 4, 2, 4, 1, QtCore.Qt.AlignHCenter)
        self.date_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout_2.addWidget(self.date_label, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.date_edit = QtWidgets.QDateEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_edit.sizePolicy().hasHeightForWidth())
        self.date_edit.setSizePolicy(sizePolicy)
        self.date_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.date_edit.setStyleSheet("QCalendarWidget QWidget { background-color: #c8beb7; }    /* calosc */ \n"
"\n"
"QCalendarWidget QWidget { alternate-background-color: #c8beb7; } /* naglowek z nazwami dni */\n"
"\n"
"QCalendarWidget QToolButton { color: black; }    /* najwyzszy naglowek - czcionka*/\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"QCalendarWidget QToolButton {\n"
"      height: 60px;\n"
"      width: 150px;\n"
"      color: white;\n"
"      font-size: 24px;\n"
"      icon-size: 56px, 56px;\n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333);\n"
"  }\n"
"*/\n"
"\n"
"/* /// to jest to rozwijane menu z miesiącami\n"
"QCalendarWidget QMenu {\n"
"      width: 150px;\n"
"      left: 20px;\n"
"      color: white;\n"
"      font-size: 18px;\n"
"      background-color: rgb(100, 100, 100);\n"
"  }\n"
"*/\n"
"\n"
"/*  ////// to jest do zmian roku\n"
"QCalendarWidget QSpinBox { \n"
"      width: 150px; \n"
"      font-size:24px; \n"
"      color: white; \n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333); \n"
"      selection-background-color: rgb(136, 136, 136);\n"
"      selection-color: rgb(255, 255, 255);\n"
"  }\n"
"  QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:65px; }\n"
"  QCalendarWidget QSpinBox::down-button {subcontrol-origin: border; subcontrol-position: bottom right;  width:65px;}\n"
"  QCalendarWidget QSpinBox::up-arrow { width:56px;  height:56px; }\n"
"  QCalendarWidget QSpinBox::down-arrow { width:56px;  height:56px; }\n"
"\n"
"*/\n"
"\n"
"\n"
"\n"
"/*\n"
"  QCalendarWidget QWidget { alternate-background-color: rgb(128, 128, 128); }\n"
"\n"
"  QCalendarWidget QAbstractItemView:enabled \n"
"  {\n"
"      color: red;     liczby - daty i nazwy dni \n"
"      background-color: #252525;  tło kalendarza \n"
"      selection-background-color: #202020; \n"
"      selection-color: #202020; \n"
"  }\n"
"*/\n"
"\n"
"\n"
"\n"
"")
        self.date_edit.setCalendarPopup(True)
        self.date_edit.setObjectName("date_edit")
        self.gridLayout_2.addWidget(self.date_edit, 3, 0, 1, 1)
        self.ok_button = QtWidgets.QPushButton(self.frame_2)
        self.ok_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.gridLayout_2.addWidget(self.ok_button, 8, 2, 1, 1)
        self.amount_label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.amount_label.setFont(font)
        self.amount_label.setObjectName("amount_label")
        self.gridLayout_2.addWidget(self.amount_label, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.categories_combobox = QtWidgets.QComboBox(self.frame_2)
        self.categories_combobox.setMinimumSize(QtCore.QSize(0, 40))
        self.categories_combobox.setObjectName("categories_combobox")
        self.gridLayout_2.addWidget(self.categories_combobox, 3, 2, 1, 1)
        self.add_expense_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_expense_label.sizePolicy().hasHeightForWidth())
        self.add_expense_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_expense_label.setFont(font)
        self.add_expense_label.setObjectName("add_expense_label")
        self.gridLayout_2.addWidget(self.add_expense_label, 0, 0, 2, 3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.amount_line_edit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_line_edit.sizePolicy().hasHeightForWidth())
        self.amount_line_edit.setSizePolicy(sizePolicy)
        self.amount_line_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.amount_line_edit.setObjectName("amount_line_edit")
        self.gridLayout_2.addWidget(self.amount_line_edit, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)

        self.retranslateUi(expenses_tab)
        QtCore.QMetaObject.connectSlotsByName(expenses_tab)

    def retranslateUi(self, expenses_tab):
        _translate = QtCore.QCoreApplication.translate
        expenses_tab.setWindowTitle(_translate("expenses_tab", "Form"))
        self.add_expense_csv_label.setText(_translate("expenses_tab", "Dodaj wydatek przez plik csv"))
        self.choose_file_label.setText(_translate("expenses_tab", "Wybierz plik:"))
        self.browse_file_button.setText(_translate("expenses_tab", "..."))
        self.ok_button_csv.setText(_translate("expenses_tab", "Zatwierdź"))
        self.categories_list_label.setText(_translate("expenses_tab", "Lista kategorii"))
        self.add_category_button.setText(_translate("expenses_tab", "Dodaj kategorię"))
        self.delete_category_button.setText(_translate("expenses_tab", "Usuń kategorię"))
        self.category_label.setText(_translate("expenses_tab", "kategoria"))
        self.date_label.setText(_translate("expenses_tab", "data"))
        self.ok_button.setText(_translate("expenses_tab", "Zatwierdź"))
        self.amount_label.setText(_translate("expenses_tab", "kwota [zł]"))
        self.add_expense_label.setText(_translate("expenses_tab", "Dodaj wydatek"))
