# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_dialog(object):
    def setupUi(self, filter_dialog):
        filter_dialog.setObjectName("filter_dialog")
        filter_dialog.resize(600, 500)
        filter_dialog.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QLineEdit { \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {    /* zmiana kolorów listy rozwijanej */\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"\n"
"QDateEdit {\n"
"background-color: #3e3e3e;\n"
"color: #c8beb7;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(filter_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(filter_dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5, QtCore.Qt.AlignHCenter)
        self.amount_min = QtWidgets.QLineEdit(filter_dialog)
        self.amount_min.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.amount_min.setFont(font)
        self.amount_min.setObjectName("amount_min")
        self.gridLayout.addWidget(self.amount_min, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(filter_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 4)
        self.date_from = QtWidgets.QDateEdit(filter_dialog)
        self.date_from.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_from.setFont(font)
        self.date_from.setStyleSheet("QCalendarWidget QWidget { background-color: #c8beb7; }    /* calosc */ \n"
"\n"
"QCalendarWidget QWidget { alternate-background-color: #c8beb7; } /* naglowek z nazwami dni */\n"
"\n"
"QCalendarWidget QToolButton { color: black; }    /* najwyzszy naglowek - czcionka*/")
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.gridLayout.addWidget(self.date_from, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(filter_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.amount_max = QtWidgets.QLineEdit(filter_dialog)
        self.amount_max.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.amount_max.setFont(font)
        self.amount_max.setObjectName("amount_max")
        self.gridLayout.addWidget(self.amount_max, 6, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 5)
        self.label_7 = QtWidgets.QLabel(filter_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.date_to = QtWidgets.QDateEdit(filter_dialog)
        self.date_to.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_to.setFont(font)
        self.date_to.setStyleSheet("QCalendarWidget QWidget { background-color: #c8beb7; }    /* calosc */ \n"
"\n"
"QCalendarWidget QWidget { alternate-background-color: #c8beb7; } /* naglowek z nazwami dni */\n"
"\n"
"QCalendarWidget QToolButton { color: black; }    /* najwyzszy naglowek - czcionka*/")
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")
        self.gridLayout.addWidget(self.date_to, 2, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(filter_dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.category_combobox = QtWidgets.QComboBox(filter_dialog)
        self.category_combobox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.category_combobox.setFont(font)
        self.category_combobox.setObjectName("category_combobox")
        self.gridLayout.addWidget(self.category_combobox, 4, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 7, 3, 1, 2)

        self.retranslateUi(filter_dialog)
        self.buttonBox.accepted.connect(filter_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(filter_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(filter_dialog)

    def retranslateUi(self, filter_dialog):
        _translate = QtCore.QCoreApplication.translate
        filter_dialog.setWindowTitle(_translate("filter_dialog", "Dialog"))
        self.label.setText(_translate("filter_dialog", "Wybierz opcje filtrowania:"))
        self.label_3.setText(_translate("filter_dialog", "od:"))
        self.label_5.setText(_translate("filter_dialog", "względem kategorii:"))
        self.label_8.setText(_translate("filter_dialog", "do:"))
        self.label_6.setText(_translate("filter_dialog", "względem przedziału kwot:"))
        self.label_7.setText(_translate("filter_dialog", "od:"))
        self.label_4.setText(_translate("filter_dialog", "do:"))
        self.label_2.setText(_translate("filter_dialog", "względem przedziału dat:"))
