# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_dialog(object):
    def setupUi(self, filter_dialog):
        filter_dialog.setObjectName("filter_dialog")
        filter_dialog.resize(600, 509)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(filter_dialog.sizePolicy().hasHeightForWidth())
        filter_dialog.setSizePolicy(sizePolicy)
        filter_dialog.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
" QCheckBox { color: #c8beb7 }\n"
"\n"
"QLineEdit { \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {    /* zmiana kolorów listy rozwijanej */\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7;\n"
"}\n"
"\n"
"\n"
"QDateEdit {\n"
"background-color: #3e3e3e;\n"
"color: #c8beb7;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(filter_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.dates_checkbox = QtWidgets.QCheckBox(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dates_checkbox.sizePolicy().hasHeightForWidth())
        self.dates_checkbox.setSizePolicy(sizePolicy)
        self.dates_checkbox.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dates_checkbox.setFont(font)
        self.dates_checkbox.setObjectName("dates_checkbox")
        self.verticalLayout_2.addWidget(self.dates_checkbox)
        self.dates_widget = QtWidgets.QWidget(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dates_widget.sizePolicy().hasHeightForWidth())
        self.dates_widget.setSizePolicy(sizePolicy)
        self.dates_widget.setMinimumSize(QtCore.QSize(580, 60))
        self.dates_widget.setObjectName("dates_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dates_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.dates_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.date_from = QtWidgets.QDateEdit(self.dates_widget)
        self.date_from.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_from.setFont(font)
        self.date_from.setStyleSheet("QCalendarWidget QWidget { background-color: #c8beb7; }    /* calosc */ \n"
"\n"
"QCalendarWidget QWidget { alternate-background-color: #c8beb7; } /* naglowek z nazwami dni */\n"
"\n"
"QCalendarWidget QToolButton { color: black; }    /* najwyzszy naglowek - czcionka*/")
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.horizontalLayout.addWidget(self.date_from)
        self.label_4 = QtWidgets.QLabel(self.dates_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.date_to = QtWidgets.QDateEdit(self.dates_widget)
        self.date_to.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_to.setFont(font)
        self.date_to.setStyleSheet("QCalendarWidget QWidget { background-color: #c8beb7; }    /* calosc */ \n"
"\n"
"QCalendarWidget QWidget { alternate-background-color: #c8beb7; } /* naglowek z nazwami dni */\n"
"\n"
"QCalendarWidget QToolButton { color: black; }    /* najwyzszy naglowek - czcionka*/")
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")
        self.horizontalLayout.addWidget(self.date_to)
        self.verticalLayout_2.addWidget(self.dates_widget)
        self.categories_checkbox = QtWidgets.QCheckBox(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories_checkbox.sizePolicy().hasHeightForWidth())
        self.categories_checkbox.setSizePolicy(sizePolicy)
        self.categories_checkbox.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.categories_checkbox.setFont(font)
        self.categories_checkbox.setObjectName("categories_checkbox")
        self.verticalLayout_2.addWidget(self.categories_checkbox)
        self.category_widget = QtWidgets.QWidget(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_widget.sizePolicy().hasHeightForWidth())
        self.category_widget.setSizePolicy(sizePolicy)
        self.category_widget.setMinimumSize(QtCore.QSize(580, 60))
        self.category_widget.setObjectName("category_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.category_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.category_combobox = QtWidgets.QComboBox(self.category_widget)
        self.category_combobox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.category_combobox.setFont(font)
        self.category_combobox.setObjectName("category_combobox")
        self.verticalLayout.addWidget(self.category_combobox)
        self.verticalLayout_2.addWidget(self.category_widget)
        self.amount_checkbox = QtWidgets.QCheckBox(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_checkbox.sizePolicy().hasHeightForWidth())
        self.amount_checkbox.setSizePolicy(sizePolicy)
        self.amount_checkbox.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.amount_checkbox.setFont(font)
        self.amount_checkbox.setObjectName("amount_checkbox")
        self.verticalLayout_2.addWidget(self.amount_checkbox)
        self.amount_widget = QtWidgets.QWidget(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_widget.sizePolicy().hasHeightForWidth())
        self.amount_widget.setSizePolicy(sizePolicy)
        self.amount_widget.setMinimumSize(QtCore.QSize(580, 60))
        self.amount_widget.setObjectName("amount_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.amount_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.amount_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.amount_min = QtWidgets.QLineEdit(self.amount_widget)
        self.amount_min.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.amount_min.setFont(font)
        self.amount_min.setObjectName("amount_min")
        self.horizontalLayout_2.addWidget(self.amount_min)
        self.label_8 = QtWidgets.QLabel(self.amount_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.amount_max = QtWidgets.QLineEdit(self.amount_widget)
        self.amount_max.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.amount_max.setFont(font)
        self.amount_max.setObjectName("amount_max")
        self.horizontalLayout_2.addWidget(self.amount_max)
        self.verticalLayout_2.addWidget(self.amount_widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(filter_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(filter_dialog)
        self.buttonBox.accepted.connect(filter_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(filter_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(filter_dialog)

    def retranslateUi(self, filter_dialog):
        _translate = QtCore.QCoreApplication.translate
        filter_dialog.setWindowTitle(_translate("filter_dialog", "Dialog"))
        self.label.setText(_translate("filter_dialog", "Wybierz opcje filtrowania:"))
        self.dates_checkbox.setText(_translate("filter_dialog", "względem przedziału dat:"))
        self.label_3.setText(_translate("filter_dialog", "od:"))
        self.label_4.setText(_translate("filter_dialog", "do:"))
        self.categories_checkbox.setText(_translate("filter_dialog", "względem kategorii:"))
        self.amount_checkbox.setText(_translate("filter_dialog", "względem przedziału kwot:"))
        self.label_7.setText(_translate("filter_dialog", "od:"))
        self.label_8.setText(_translate("filter_dialog", "do:"))
