# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zuzanna/Wydatkoinator/ui/home_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_tab(object):
    def setupUi(self, home_tab):
        home_tab.setObjectName("home_tab")
        home_tab.resize(1145, 693)
        home_tab.setStyleSheet("QWidget { background-color: #202020 }")
        self.gridLayout = QtWidgets.QGridLayout(home_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.chart1 = QChartView(home_tab)
        self.chart1.setObjectName("chart1")
        self.gridLayout.addWidget(self.chart1, 0, 0, 1, 1)
        self.chart2 = QChartView(home_tab)
        self.chart2.setObjectName("chart2")
        self.gridLayout.addWidget(self.chart2, 1, 0, 1, 1)

        self.retranslateUi(home_tab)
        QtCore.QMetaObject.connectSlotsByName(home_tab)

    def retranslateUi(self, home_tab):
        _translate = QtCore.QCoreApplication.translate
        home_tab.setWindowTitle(_translate("home_tab", "Form"))
from PyQt5.QtChart import QChartView
