# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kubus/Pulpit/Wydatkoinator/ui/modify_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modify_csv(object):
    def setupUi(self, modify_csv):
        modify_csv.setObjectName("modify_csv")
        modify_csv.resize(700, 700)
        modify_csv.setStyleSheet("QDialog { background-color: #202020 }\n"
"\n"
"QLabel { color: #c8beb7 }\n"
"\n"
"QPlainTextEdit { \n"
"    color: #c8beb7;\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QScrollBar {\n"
"    background-color: #3e3e3e\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #3e3e3e;\n"
"    color: #c8beb7\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(modify_csv)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(modify_csv)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plain_text_modify = QtWidgets.QPlainTextEdit(modify_csv)
        self.plain_text_modify.setObjectName("plain_text_modify")
        self.verticalLayout.addWidget(self.plain_text_modify)
        self.buttonBox = QtWidgets.QDialogButtonBox(modify_csv)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(modify_csv)
        self.buttonBox.accepted.connect(modify_csv.accept) # type: ignore
        self.buttonBox.rejected.connect(modify_csv.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(modify_csv)

    def retranslateUi(self, modify_csv):
        _translate = QtCore.QCoreApplication.translate
        modify_csv.setWindowTitle(_translate("modify_csv", "Dialog"))
        self.label.setText(_translate("modify_csv", "Usuń niepotrzebne wiersze na początku i na końcu pliku csv (zostaw wiersz z nagłówkami i z wartościowymi danymi, które będą wpisane do bazy)"))
